name: coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    # TODO: skip this one for commits that don't touch py or rust code?
    # maybe make it opt-in?
    steps:
      - uses: actions/checkout@v4
        # TODO: use tags or some other way to reference known-good version?
      - uses: actions/checkout@v4
        with:
          path: '_validation'
          repository: prunepytest/prunepytest-validation
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: dtolnay/rust-toolchain@1.83
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov, cargo-nextest
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Run all tests
        run: |
          set -ex
          export MATURIN_FLAGS="--compatibility=linux --auditwheel=skip"
          EXTRA_TESTS=_validation/runtests.sh RUST_COVERAGE=1 ./runtests.sh
          mkdir artifacts
          mv target/llvm-cov/html cov.merged.json lcov.info artifacts/
      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v5
        with:
          disable_search: 'true'
          verbose: 'true'
          files: artifacts/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: prunepytest/prunepytest
      - name: Upload coverage results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: artifacts
